name: Validate Mamba Environment

on:
  workflow_dispatch:
  push:
    paths:
      - 'env.yaml'
      - '.github/workflows/validate-mamba-env.yml'
  pull_request:
    paths:
      - 'env.yaml'
      - '.github/workflows/validate-mamba-env.yml'

jobs:
  validate-environment:
    name: Validate Environment Setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: env.yaml
        init-shell: bash

    - name: Verify Environment
      shell: bash -el {0}
      run: |
        micromamba activate torch-provlae
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torchvision; print('Torchvision:', torchvision.__version__)"

    - name: List Environment Info
      if: always()
      shell: bash -el {0}
      run: |
        micromamba list